In [1]:
import pandas as pd
import random

from numpy import array
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.

In [2]:
data = pd.read_csv('Fortune500_financial_quarter_data_1961_2019.csv')

In [8]:
some = data.drop('conm', 1).isna().groupby(data.conm, sort=False).sum().reset_index()

In [27]:
other = some[some['prccq'] == 0]

In [29]:
list(other['conm'].unique())

array(['PINNACLE WEST CAPITAL CORP', 'ABBOTT LABORATORIES', 'AETNA INC',
       'AIR PRODUCTS & CHEMICALS INC', 'HONEYWELL INTERNATIONAL INC',
       'SKYWORKS SOLUTIONS INC', 'HESS CORP',
       'AMERICAN ELECTRIC POWER CO', 'AMERICAN EXPRESS CO', 'AFLAC INC',
       'AMERICAN INTERNATIONAL GROUP', 'AMETEK INC', 'APACHE CORP',
       'APPLIED MATERIALS INC', 'ARCHER-DANIELS-MIDLAND CO',
       'AUTOMATIC DATA PROCESSING', 'AVERY DENNISON CORP',
       'BAKER HUGHES INC', 'BARD (C.R.) INC', 'BAXTER INTERNATIONAL INC',
       'BECTON DICKINSON & CO', 'VERIZON COMMUNICATIONS INC', 'BOEING CO',
       'ROBERT HALF INTL INC', 'BRISTOL-MYERS SQUIBB CO', 'CIGNA CORP',
       'CONSTELLATION BRANDS', 'CATERPILLAR INC', 'JPMORGAN CHASE & CO',
       'CHEVRON CORP', 'COCA-COLA CO', 'COLGATE-PALMOLIVE CO', 'AON PLC',
       'COMCAST CORP', 'COMERICA INC', 'CONSOLIDATED EDISON INC',
       'CMS ENERGY CORP', 'CORNING INC', 'CUMMINS INC', 'DANAHER CORP',
       'DEERE & CO', 'DTE ENERGY CO', 'DISNEY (WALT) CO',
       'DOMINION ENERGY INC', 'DOVER CORP', 'DUPONT DE NEMOURS INC',
       'OMNICOM GROUP', 'DUKE ENERGY CORP', 'FLOWSERVE CORP',
       'PERKINELMER INC', 'EATON CORP PLC', 'EMERSON ELECTRIC CO',
       'EQUIFAX INC', 'EQT CORP', 'EXXON MOBIL CORP', 'FMC CORP',
       'NEXTERA ENERGY INC', 'FIFTH THIRD BANCORP', 'FLUOR CORP',
       'FORD MOTOR CO', 'FRANKLIN RESOURCES INC', 'GENERAL DYNAMICS CORP',
       'GENERAL ELECTRIC CO', 'GENERAL MOTORS CO', 'GENUINE PARTS CO',
       'GOODYEAR TIRE & RUBBER CO', 'GRAINGER (W W) INC',
       'HALLIBURTON CO', 'HELMERICH & PAYNE', 'HERSHEY CO', 'HP INC',
       'HORMEL FOODS CORP', 'STARWOOD HOTELS&RESORTS WRLD',
       'CENTERPOINT ENERGY INC', 'ILLINOIS TOOL WORKS', 'INTEL CORP',
       'INTL BUSINESS MACHINES CORP', 'INTL FLAVORS & FRAGRANCES',
       'INTL PAPER CO', 'INTERPUBLIC GROUP OF COS', 'JOHNSON & JOHNSON',
       'JOHNSON CONTROLS INTL PLC', 'KLA CORP', 'KANSAS CITY SOUTHERN',
       'KELLOGG CO', 'KIMBERLY-CLARK CORP', 'KROGER CO',
       'LEGGETT & PLATT INC', 'LILLY (ELI) & CO', 'L BRANDS INC',
       'LINCOLN NATIONAL CORP', 'LOCKHEED MARTIN CORP', "LOWE'S COS INC",
       'MARSH & MCLENNAN COS', 'MASCO CORP', 'MCCORMICK & CO INC',
       'MCKESSON CORP', 'MEDTRONIC PLC', 'CVS HEALTH CORP', 'MERCK & CO',
       'ENTERGY CORP', 'MOTOROLA SOLUTIONS INC', 'MURPHY OIL CORP',
       'MYLAN NV', 'NEWELL BRANDS INC', 'NEWMONT CORP', 'NIKE INC  -CL B',
       'NOBLE ENERGY INC', 'NORDSTROM INC', 'NORFOLK SOUTHERN CORP',
       'NISOURCE INC', 'XCEL ENERGY INC', 'WELLS FARGO & CO',
       'NUCOR CORP', 'OCCIDENTAL PETROLEUM CORP', 'FIRSTENERGY CORP',
       'ONEOK INC', 'PNC FINANCIAL SVCS GROUP INC', 'PPG INDUSTRIES INC',
       'PACCAR INC', 'PG&E CORP', 'SEMPRA ENERGY', 'PARKER-HANNIFIN CORP',
       'PPL CORP', 'PENTAIR PLC', 'PFIZER INC', 'EXELON CORP',
       'ALTRIA GROUP INC', 'CONOCOPHILLIPS', 'PVH CORP',
       'PITNEY BOWES INC', 'PEPCO HOLDINGS INC',
       'PRECISION CASTPARTS CORP', 'PUBLIC SERVICE ENTRP GRP INC',
       'RAYTHEON CO', 'RYDER SYSTEM INC', 'ST JUDE MEDICAL INC',
       'SCANA CORP', 'SCHLUMBERGER LTD', 'SEALED AIR CORP',
       'SHERWIN-WILLIAMS CO', 'SIGMA-ALDRICH CORP', 'SMUCKER (JM) CO',
       'SNAP-ON INC', 'EDISON INTERNATIONAL', 'SOUTHERN CO', 'AT&T INC',
       'SOUTHWESTERN ENERGY CO', 'STANLEY BLACK & DECKER INC',
       'STATE STREET CORP', 'PUBLIC STORAGE', 'STRYKER CORP',
       'TECO ENERGY INC', 'TEXAS INSTRUMENTS INC', 'TEXTRON INC',
       'THERMO FISHER SCIENTIFIC INC', 'TYCO INTERNATIONAL PLC',
       'TYSON FOODS INC  -CL A', 'AMEREN CORP', 'UNION PACIFIC CORP',
       'VF CORP', 'VARIAN MEDICAL SYSTEMS INC', 'VULCAN MATERIALS CO',
       'WALGREENS BOOTS ALLIANCE INC', 'WESTERN DIGITAL CORP',
       'WEYERHAEUSER CO', 'WHIRLPOOL CORP', 'WILLIAMS COS INC',
       'WEC ENERGY GROUP INC', 'XEROX HOLDINGS CORP',
       'ZIONS BANCORPORATION NA', 'JOY GLOBAL INC',
       'PROGRESSIVE CORP-OHIO', 'CINCINNATI FINANCIAL CORP',
       'DEVON ENERGY CORP'], dtype=object)

In [74]:
companies = list(other['conm'].unique())
random25 = random.sample(companies, 25)

In [75]:
random25

['FIRSTENERGY CORP',
 'PROGRESSIVE CORP-OHIO',
 'DTE ENERGY CO',
 'ALTRIA GROUP INC',
 'NEXTERA ENERGY INC',
 'INTL PAPER CO',
 'SCHLUMBERGER LTD',
 'DISNEY (WALT) CO',
 'XEROX HOLDINGS CORP',
 'CONOCOPHILLIPS',
 'BOEING CO',
 'EXXON MOBIL CORP',
 'THERMO FISHER SCIENTIFIC INC',
 'GENUINE PARTS CO',
 'INTEL CORP',
 'MEDTRONIC PLC',
 'EMERSON ELECTRIC CO',
 'VF CORP',
 'ENTERGY CORP',
 'KIMBERLY-CLARK CORP',
 'L BRANDS INC',
 'COMERICA INC',
 'SCANA CORP',
 'EDISON INTERNATIONAL',
 'PFIZER INC']

In [76]:
hwdata = data.loc[data['conm'].isin(random25)]

In [77]:
hwdata = hwdata.reset_index(drop = True)

In [78]:
hwdata

,datadate,tic,conm,datacqtr,atq,chq,cogsq,dlttq,ibq,invtq,saleq,xrdq,xsgaq,prccq
0,19620331,BA,BOEING CO,1962Q1,NaN,NaN,NaN,NaN,8.041,NaN,466.8,NaN,NaN,50.1250
1,19620630,BA,BOEING CO,1962Q2,NaN,NaN,NaN,NaN,7.439,NaN,366.9,NaN,NaN,36.7500
2,19620930,BA,BOEING CO,1962Q3,NaN,NaN,NaN,NaN,6.099,NaN,434.7,NaN,NaN,37.9999
3,19621231,BA,BOEING CO,1962Q4,NaN,NaN,NaN,NaN,5.575,NaN,500.1,NaN,NaN,37.1249
4,19630331,BA,BOEING CO,1963Q1,NaN,NaN,NaN,NaN,4.410,NaN,483.8,NaN,NaN,36.2499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5468,20181231,PGR,PROGRESSIVE CORP-OHIO,2018Q4,46575.0,69.5,7666.0,4404.9,264.700,0.0,8028.8,NaN,NaN,60.3300
5469,20190331,PGR,PROGRESSIVE CORP-OHIO,2019Q1,48850.3,158.0,7608.4,4616.8,1078.400,0.0,9293.8,NaN,NaN,72.0900
5470,20190630,PGR,PROGRESSIVE CORP-OHIO,2019Q2,51324.2,91.9,8073.5,4610.2,979.400,0.0,9444.5,NaN,NaN,79.9300
5471,20190930,PGR,PROGRESSIVE CORP-OHIO,2019Q3,54008.1,45.9,8394.6,4610.6,841.700,0.0,9524.6,NaN,NaN,77.2500
5472,20191231,PGR,PROGRESSIVE CORP-OHIO,2019Q4,54895.3,226.2,9265.1,4608.6,1070.800,0.0,10734.8,NaN,NaN,72.3900

In [79]:
hwdata.groupby('conm').count()

,datadate,tic,datacqtr,atq,chq,cogsq,dlttq,ibq,invtq,saleq,xrdq,xsgaq,prccq
conm,,,,,,,,,,,,,
ALTRIA GROUP INC,232,232,232,183,56,182,195,232,172,232,31,182,232
BOEING CO,232,232,232,181,52,183,197,232,181,232,115,93,232
COMERICA INC,232,232,232,232,0,208,184,212,147,212,0,212,232
CONOCOPHILLIPS,232,232,232,181,52,204,195,232,181,232,30,203,232
DISNEY (WALT) CO,233,233,233,185,53,184,193,233,170,231,0,21,233
DTE ENERGY CO,232,232,232,196,172,172,196,232,172,232,0,0,232
EDISON INTERNATIONAL,232,232,232,196,171,172,196,232,171,232,0,0,232
EMERSON ELECTRIC CO,233,233,233,182,53,178,196,231,182,231,31,184,233
ENTERGY CORP,232,232,232,196,172,172,196,232,172,232,0,0,232
EXXON MOBIL CORP,232,232,232,184,52,201,195,232,184,232,31,201,232
FIRSTENERGY CORP,232,232,232,196,172,172,196,217,172,217,0,0,232
GENUINE PARTS CO,216,216,216,182,56,185,198,216,175,216,44,177,216
INTEL CORP,192,192,192,183,52,180,186,192,183,192,124,180,192
INTL PAPER CO,232,232,232,184,52,204,204,232,184,232,30,204,232
KIMBERLY-CLARK CORP,228,228,227,184,52,183,195,228,184,228,70,180,228
L BRANDS INC,171,171,171,171,51,171,171,171,171,171,11,171,171
MEDTRONIC PLC,206,206,206,182,44,183,137,206,182,206,122,185,206
NEXTERA ENERGY INC,232,232,232,196,172,172,196,232,172,232,0,0,232
PFIZER INC,232,232,232,181,52,187,195,230,181,230,124,192,232
PROGRESSIVE CORP-OHIO,140,140,140,140,52,140,140,140,140,140,0,0,140
SCANA CORP,227,227,227,192,167,167,192,227,167,227,0,0,227
SCHLUMBERGER LTD,232,232,232,172,52,200,174,232,171,232,124,202,232
THERMO FISHER SCIENTIFIC INC,164,164,164,164,52,163,164,164,164,164,122,144,164
VF CORP,215,215,215,180,51,182,194,214,180,214,0,182,215
XEROX HOLDINGS CORP,232,232,232,181,52,178,195,231,181,231,123,155,232

In [80]:
hwdata.to_csv('hwdata.csv')